exp:
    title: "jsai-dev-01" # exp(実験)までもいかない開発状態
    llms: [
          "rinna/gemma-2-baku-2b-it", # in llm-jp-bench
          "llm-jp/llm-jp-3-1.8b-instruct", # in llm-jp-bench
          "llm-jp/llm-jp-3-13b-instruct", # in llm-jp-bench
          "llm-jp/llm-jp-3-3.7b-instruct", # in llm-jp-bench
          "meta-llama/Llama-3.2-1B-Instruct",# in llm-jp-bench
          "meta-llama/Llama-3.2-3B-Instruct",# in llm-jp-bench
          "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B",# in llm-jp-bench
          "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B",# in llm-jp-bench
          "deepseek-ai/DeepSeek-R1-Distill-Llama-8B",# in llm-jp-bench
          "Qwen/Qwen2.5-7B-Instruct", # in llm-jp-bench
          "Qwen/Qwen2.5-3B-Instruct", # in llm-jp-bench
          "Qwen/Qwen2.5-1.5B-Instruct", # in llm-jp-bench
          "Qwen/Qwen2.5-0.5B-Instruct", # in llm-jp-bench
          "google/gemma-2-9b-it",# in llm-jp-bench
          "google/gemma-2-2b-it",# in llm-jp-bench
          "HuggingFaceTB/SmolLM2-135M-Instruct",# in llm-jp-bench
          "HuggingFaceTB/SmolLM2-1.7B-Instruct",# in llm-jp-bench
          "ibm-granite/granite-3.1-8b-instruct",# in llm-jp-bench
          "ibm-granite/granite-3.1-3b-a800m-instruct",# in llm-jp-bench
          "ibm-granite/granite-3.1-2b-instruct",# in llm-jp-bench
          "ibm-granite/granite-3.1-1b-a400m-instruct",# in llm-jp-bench
         ]
    inputs: "../resume-data/doda-samples"
    inputs_limit: 100
    log_dir: "./dev_log"
    device: "auto"
    use_cache: True

cache:
    enable: True
    top_dir: "CacheStorage"
    root: "defaultCache"


