exp:
    title: "ipsj2026-exp05"
    summary: "IPSJ2026投稿用実験の前のデバグ用．all_models.shで実行したログが，mlflow GUIには出るのにmlflow.clientで取得できない．締め切り近いのに3日以上悩んでる"
    llm: "google/gemma-1.1-7b-it" # 呼び出しシェルから上書きされる
    input: "./kaggle-resume/12635195.txt" # 呼び出しシェルから上書きされる
    inputs_limit: 100
    log_dir: "./dev_log"
    device: "auto"
    use_cache: False # KV cache
    hosting: "huggingface" # or "openai", "vllm"
    max_vocab_size: 200000 # VR-LMCR計算用の語彙数基準値
    gamma: 1.0 # VR-LMCR計算用パラメータ

cache:
    enable: True
    top_dir: "CacheStorage"
    root: "ipsj2026"


