exp:
    title: "fit2025-paper-07"
    summary: "LLM6個に絞って入力長変化実験"
    llm: "google/gemma-1.1-7b-it"
    input: "./kaggle-resume/12635195.txt"
    inputs_limit: 100
    log_dir: "./dev_log"
    device: "auto"
    use_cache: False # KV cache
    hosting: "huggingface" # or "openai", "vllm"

cache:
    enable: True
    top_dir: "CacheStorage"
    root: "fit2025"


