exp:
    title: "fit2025-paper-01(vllm)" # exp(実験)までもいかない開発状態
    summary: "vLLM導入とかいろいろのための，速度検証用にちょっと長い入力"
    llm: "meta-llama/Llama-3.2-3B-Instruct"
    #input: "test-input-data/minimum.txt"
    input: "../resume-data/doda-samples/職務経歴書サンプル_ITエンジニア_ITコンサルタント.txt"
    inputs_limit: 100
    log_dir: "./dev_log"
    device: "auto"
    use_cache: True

cache:
    enable: True
    top_dir: "CacheStorage"
    root: "defaultCache"


