exp:
    summary: "IPSJ2026の論文投稿用の実験．言語モデルを並べてL2キャッシュを溜める用"
    #title: "ipsj2026_paper_04"
    run_suffix: "" # Run名に付与する補足説明 (e.g. "ae" -> title(ae))
    llm: "google/gemma-1.1-7b-it" # 呼び出しシェルから上書きされる
    input: "./kaggle-resume/12635195.txt" # 呼び出しシェルから上書きされる
    inputs_limit: 100
    log_dir: "./log_ipsj2026paper"
    device: "auto"
    #device: "cpu"
    use_cache: True # KV cache
    hosting: "huggingface" # or "openai", "vllm"
    max_vocab_size: 200000 # VR-LMCR計算用の語彙数基準値
    gamma: 1.0 # VR-LMCR計算用パラメータ
    clear_previous_runs: True  # 実験開始時に同じexp_titleの過去のrunを削除するか
    encoding_algorithm: "ae" # or "ppl" 

cache:
    l1_cache:
        enable: False
        overwrite: False
        top_dir: "CacheStorage"
        root: "ipsj2026_paper"
    l2_cache:
        enable: True
        overwrite: True
        top_dir: "CacheStorage_LLM"

exp_models:
  target_models:
    - "google/gemma-1.1-2b-it"
    - "google/gemma-1.1-7b-it"
    - "google/gemma-2-27b-it"
    - "google/gemma-2b-it"
    - "google/gemma-7b-it"
    - "HuggingFaceTB/SmolLM2-1.7B-Instruct"
    - "llm-jp/llm-jp-3-440m-instruct2"
    - "llm-jp/llm-jp-3-980m-instruct2"
    - "llm-jp/llm-jp-3-1.8b-instruct"
    - "llm-jp/llm-jp-3-3.7b-instruct"
    - "llm-jp/llm-jp-3-3.7b-instruct2"
    - "llm-jp/llm-jp-3-13b-instruct"
    - "llm-jp/llm-jp-3.1-1.8b-instruct4"
    - "llm-jp/llm-jp-3.1-13b-instruct4"
    - "meta-llama/Llama-2-7b-chat-hf"
    - "meta-llama/Llama-3.1-8B-Instruct"
    - "meta-llama/Llama-3.2-3B-Instruct"
    - "meta-llama/Meta-Llama-3-8B-Instruct"
    - "Qwen/Qwen1.5-0.5B-Chat"
    - "Qwen/Qwen1.5-4B-Chat"
    - "Qwen/Qwen1.5-14B-Chat"
    - "Qwen/Qwen1.5-32B-Chat"
    - "Qwen/Qwen2-0.5B-Instruct"
    - "Qwen/Qwen2-1.5B-Instruct"
    - "Qwen/Qwen2.5-0.5B-Instruct"
    - "Qwen/Qwen2.5-1.5B-Instruct"
    - "Qwen/Qwen2.5-3B-Instruct"
    - "Qwen/Qwen2.5-7B-Instruct"
    - "Qwen/Qwen2.5-14B-Instruct"
    - "Qwen/Qwen2.5-32B-Instruct"
    - "tiiuae/Falcon3-1B-Instruct"
    - "tiiuae/Falcon3-3B-Instruct"
    - "tiiuae/Falcon3-7B-Instruct"
    - "weblab-GENIAC/Tanuki-8B-dpo-v1.0"